# configuration service.
#
#       -  A configuration service which completelty loads the configuration for the services
#          from the local file server of the config service.
#
#       -  A configuraton service that uses a git-based repository to read the files from
####################################
management:
    security:
        enabled: false
server:
  port: 8888
#spring:
#  cloud:
#    config:
#      server:
#        encrypt.enabled: false
#        git:
#          uri: https://github.com/carnellj/config-repo/
#          searchPaths: licensingservice,organizationservice
#          username: native-cloud-apps
#          password: 0ffended

####
#Classpath and file-based solution
####

spring:
  profiles:
    active: native
  cloud:
     config:
       server:
           native:
               searchLocations: classpath:config/,classpath:config/alfa.microservice
#              searchLocations: file://<chapter 3>/confsvr/src/main/resources/config/licensingservice,
#                               file://<chapter 3>confsvr/src/main/resources/config/organizationservice

